version: '3'

services:
    db:
        image: mariadb:latest
        container_name: ${PROJECT_NAME}_db
        restart: always
        env_file:
            - .env
        environment: 
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD    
        ports:
            - '33061:3306'    
        volumes:
            - ./db/data:/var/lib/mysql
            - ./db/sql:/mnt/files/sql

    phpfpm:
        build: 
            context: ./docker/php
            dockerfile: Dockerfile
        container_name: ${PROJECT_NAME}_phpfpm
        restart: always
        volumes:
            - ./src/:/var/www/html
        depends_on: 
            - db

    web:
        build: 
            context: ./docker/nginx
            dockerfile: Dockerfile
        container_name: ${PROJECT_NAME}_web
        restart: unless-stopped
        ports:
            - '8081:80'
        working_dir: /var/www/html    
        volumes:
            - ./src:/var/www/html
        depends_on:
            - phpfpm
    
    phpmyadmin:
        image: phpmyadmin
        container_name: ${PROJECT_NAME}_phpmyadmin
        restart: always
        environment: 
            - PMA_HOST=db
            - PMA_PORT=3306
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - '8082:80'
        depends_on: 
            - db
        

networks: 
    default:
        driver: bridge
        

